# docker-compose.yml
version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      retries: 5

  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:POSTGRES_PASSWORD@db:5432/postgres
      ALEMBIC_URL: postgresql+psycopg://postgres:POSTGRES_PASSWORD@db:5432/postgres
      APP_ENV: prod
    volumes:
      - .:/app            # remove in production if you don't need live reload
    command: ["./docker-entrypoint.sh"]

volumes:
  db_data:
